# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0broute.proto\x12\x05myapp\"$\n\x05Route\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\"\n\x0cQueryRequest\x12\x12\n\nissue_date\x18\x01 \x01(\t2f\n\x0cRouteService\x12(\n\x06upload\x12\x0c.myapp.Route\x1a\x0c.myapp.Route\"\x00(\x01\x12,\n\x05query\x12\x13.myapp.QueryRequest\x1a\x0c.myapp.Route\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROUTE._serialized_start=22
  _ROUTE._serialized_end=58
  _QUERYREQUEST._serialized_start=60
  _QUERYREQUEST._serialized_end=94
  _ROUTESERVICE._serialized_start=96
  _ROUTESERVICE._serialized_end=198
# @@protoc_insertion_point(module_scope)
